### ISSUE TITLE
IMU and GNSS  OEM

### ISSUE THREAD

**Issue by iceberg1369** [SihanWang-WHU/GNSS_INS_LooseCouple#2]
what is part number of IMU model and GNSS is used for datasets collection?
is any GNSS base station is used for positioning?

**Comment by SihanWang-WHU** [comment]
It's AsteRx SBi, which combines GPS/GNSS and an industry-grade IMU (Inertial Measurement Unit) to deliver precise positioning together with 3D attitude (heading, roll, pitch). You can check out this link https://www.directindustry-china.cn/prod/septentrio/product-183002-2282177.html for more info. 
In order to calculate the RTK result, a GNSS base state is used, the coordinate is latitude(30.528441628 deg),  longitude(114.35697689 deg), and height (41.2160m). This can be checked in the Config.h file.

**Comment by iceberg1369** [comment]
do you know the part number of exact IMU model which is used inside AsteRx SBi?

**Comment by SihanWang-WHU** [comment]
sry, I have no idea about the exact IMU model used in SBi. 
I have attached some useful parameters of this IMU, hope this will help you :-)
![SBI_IMU](https://user-images.githubusercontent.com/100557045/174485415-376d90a1-2243-4224-a555-559b44e142bf.png)

**Comment by iceberg1369** [comment]
What is heading accuracy of implemented ekf model?

**Comment by SihanWang-WHU** [comment]
It depends on the accuracy of the RTK result. If most epochs are fixed solutions, the heading error is within 2 degrees compared to the ground truth.

**Comment by iceberg1369** [comment]
2  degree is far off from 0.2 degree from onboard solution. What  could be the reason?

**Comment by SihanWang-WHU** [comment]
Maybe it's because of some error in the parameter setting of IMU, as the 21 dimension state vector is more sensitive to these paras than the 15 dimension state vector. 
Moreover, the method of initial alignment can significantly influence the accuracy of the heading.
The accuracy will be greater if the program can apply the backward RTS filter.

**Comment by iceberg1369** [comment]
it seems like just coarse alignment is carried out. And no fine alignment present
